# Generated by Django 5.1.1 on 2024-10-10 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedetails',
            old_name='value',
            new_name='about',
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='address',
            field=models.CharField(default='City, Country', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='email',
            field=models.CharField(default='mail@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='partner',
            field=models.CharField(default='https://tmbmnadim.blogspot.com/', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='phone',
            field=models.CharField(default='090909090', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('site_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sitedetails')),
            ],
        ),
    ]
