# Generated by Django 5.1.1 on 2025-04-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomercetest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_stock',
            new_name='stock',
        ),
    ]
